// Generated by the contract-artifacts CLI. Do not edit.
// Release evm/comakery_security_token_v5_1/unreleased.
//
// The merged call surfaces. A token forwards unknown selectors into its
// extensions, so a caller that talks to the token address needs this
// rather than the token ABI alone.
'use strict'
exports.restrictedLockupTokenAbi = require('../abi/merged/RestrictedLockupToken.json')
