// Generated by the contract-artifacts CLI. Do not edit.
// Release evm/comakery_security_token_v5_1/unreleased.
//
// The merged call surfaces. A token forwards unknown selectors into its
// extensions, so a caller that talks to the token address needs this
// rather than the token ABI alone.
export declare const restrictedLockupTokenAbi: readonly [
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "commencedTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "currentTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "scheduleId_";
        readonly type: "uint256";
      }
    ];
    readonly name: "calculateUnlocked";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "commencedTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "currentTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly components: readonly [
          {
            readonly internalType: "uint256";
            readonly name: "releaseCount";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "delayUntilFirstReleaseInSeconds";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "initialReleasePortionInBips";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "periodBetweenReleasesInSeconds";
            readonly type: "uint256";
          }
        ];
        readonly internalType: "struct Storage.ReleaseSchedule";
        readonly name: "releaseSchedule_";
        readonly type: "tuple";
      }
    ];
    readonly name: "calculateUnlocked";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "pure";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly components: readonly [
          {
            readonly internalType: "address";
            readonly name: "transferRules";
            readonly type: "address";
          },
          {
            readonly internalType: "address";
            readonly name: "accessControl";
            readonly type: "address";
          },
          {
            readonly internalType: "address";
            readonly name: "snapshotPeriods";
            readonly type: "address";
          },
          {
            readonly internalType: "address";
            readonly name: "trustedForwarder";
            readonly type: "address";
          },
          {
            readonly internalType: "address";
            readonly name: "identityRegistry";
            readonly type: "address";
          },
          {
            readonly internalType: "address";
            readonly name: "restrictedLockupTokenManagementExtension";
            readonly type: "address";
          },
          {
            readonly internalType: "address";
            readonly name: "restrictedLockupTokenExtension";
            readonly type: "address";
          },
          {
            readonly internalType: "address";
            readonly name: "restrictedLockupTokenStandardsExtension";
            readonly type: "address";
          },
          {
            readonly internalType: "string";
            readonly name: "symbol";
            readonly type: "string";
          },
          {
            readonly internalType: "string";
            readonly name: "name";
            readonly type: "string";
          },
          {
            readonly internalType: "uint8";
            readonly name: "decimals";
            readonly type: "uint8";
          },
          {
            readonly internalType: "uint256";
            readonly name: "maxTotalSupply";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "minTimelockAmount";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "maxReleaseDelay";
            readonly type: "uint256";
          },
          {
            readonly internalType: "bool";
            readonly name: "recordMintTimestamp";
            readonly type: "bool";
          }
        ];
        readonly internalType: "struct RestrictedLockupToken.ConstructorParams";
        readonly name: "params";
        readonly type: "tuple";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "constructor";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "spender";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "allowance";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "needed";
        readonly type: "uint256";
      }
    ];
    readonly name: "ERC20InsufficientAllowance";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "sender";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "balance";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "needed";
        readonly type: "uint256";
      }
    ];
    readonly name: "ERC20InsufficientBalance";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "approver";
        readonly type: "address";
      }
    ];
    readonly name: "ERC20InvalidApprover";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "receiver";
        readonly type: "address";
      }
    ];
    readonly name: "ERC20InvalidReceiver";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "sender";
        readonly type: "address";
      }
    ];
    readonly name: "ERC20InvalidSender";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "spender";
        readonly type: "address";
      }
    ];
    readonly name: "ERC20InvalidSpender";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveReserveAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveTransferAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EasyAccessControl_InvalidZeroAddress";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "ReentrancyGuardReentrantCall";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_AddressAlreadyHasHolder";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_AlreadySet";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_AmountExceedsUnlockedBalance";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_AmountLessThanReleaseCount";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_BalanceCheckFailed";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_CannotExceedMaxTotalSupply";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_CannotRemoveHolderWithActiveTimelocks";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_CannotRemoveLastWallet";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_CantVestAllForMultipleReleases";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_CommencementTimestampDoesNotMatch";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "expected";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "actual";
        readonly type: "uint256";
      }
    ];
    readonly name: "RestrictedLockupToken_ExtensionSlotsPerWordMismatch";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_HolderAddressDoesNotExist";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_HolderAlreadyExists";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_HolderDoesNotExist";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_HoldingIndexOutOfBound";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InitialReleaseOutOfRange";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InsufficientBurnableBalance";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InsufficientTotalBalanceOf";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidAccessControl";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidAddressArray";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidAmount";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidFirstRelease";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidFundAddress";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidFundAmount";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidHolding";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidHoldingIndex";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidIdentityRegistry";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidMinTimelockAmount";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidName";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidNumberOfRelases";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidRInitialReleaseBIPS";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidReclaimTo";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidReleasePeriod";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidReleasePortionForSingleRelease";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidRestrictedLockupTokenExtension";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidRestrictedLockupTokenManagementExtension";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidRestrictedLockupTokenStandardsExtension";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidScheduleId";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidSymbol";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidTimelock";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidTokenType";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidTransferRules";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidTrustedForwarder";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidZeroAddress";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_InvalidZeroAmount";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_MaxCancelersExceeded";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_MaxHolderAddressesReached";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_MaxHolderCountReached";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_MaxTimelocksExceeded";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_MaxTotalSupplyTooLarge";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_MismatchedArrayLength";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_NewHolderMaxMustExceedCurrentHolderCount";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_NewIdentityRegistryContractDoesNotImplementIIdentityRegistry";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_NewMaxTotalSupplyMustExceedCurrentTotalSupply";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_NewTransferRulesContractDoesNotImplementITransferRules";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_NoHoldingWithEnoughBalance";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_NoItemWithEnoughBalance";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_RecipientAndAmountLengthsShouldMatch";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "reclaimTokenTo";
        readonly type: "address";
      }
    ];
    readonly name: "RestrictedLockupToken_ReclaimToFrozen";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_SafeApprove";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_ScheduleIdDoesNotMatch";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "sender";
        readonly type: "address";
      }
    ];
    readonly name: "RestrictedLockupToken_SenderCannotBeRecipient";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_TimelockCannotBeCanceled";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_TimelockHasNoValueRemaining";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_TokenTypeNotAllowedForRecipient";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_TotalAmountDoesNotMatch";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RestrictedLockupToken_TransfersPaused";
    readonly type: "error";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "bool";
        readonly name: "status";
        readonly type: "bool";
      }
    ];
    readonly name: "AddressFrozen";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "holderId";
        readonly type: "uint256";
      }
    ];
    readonly name: "AppendHolderAddress";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "owner";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "spender";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "value";
        readonly type: "uint256";
      }
    ];
    readonly name: "Approval";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "from";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "to";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      }
    ];
    readonly name: "ForceTransferBetween";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "appendedDays";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "highestDays";
        readonly type: "uint256";
      }
    ];
    readonly name: "GlobalRegistryBecameUnordered";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "holderId";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "HolderCreated";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "wallet";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "oldTokenType";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "newTokenType";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "mintTimestamp";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      }
    ];
    readonly name: "HoldingTokenTypeUpdated";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "bool";
        readonly name: "status";
        readonly type: "bool";
      }
    ];
    readonly name: "Pause";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "holderId";
        readonly type: "uint256";
      }
    ];
    readonly name: "RemoveHolder";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "holderId";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "RemoveWalletFromHolder";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "from";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "scheduleId";
        readonly type: "uint256";
      }
    ];
    readonly name: "ScheduleCreated";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "from";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "to";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "scheduleId";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "commencementTimestamp";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "timelockId";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "address[]";
        readonly name: "cancelableBy";
        readonly type: "address[]";
      }
    ];
    readonly name: "ScheduleFunded";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "holderMax";
        readonly type: "uint256";
      }
    ];
    readonly name: "SetHolderMax";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "maxTotalSupply";
        readonly type: "uint256";
      }
    ];
    readonly name: "SetMaxTotalSupply";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "canceledBy";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "target";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timelockIndex";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "address";
        readonly name: "reclaimTokenTo";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "canceledAmount";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "paidAmount";
        readonly type: "uint256";
      }
    ];
    readonly name: "TimelockCanceled";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "wallet";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timelockIndex";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "oldTokenType";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "newTokenType";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      }
    ];
    readonly name: "TimelockTokenTypeUpdated";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "wallet";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "tokenType";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "holdingsMerged";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "totalAmount";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "newMintTimestamp";
        readonly type: "uint256";
      }
    ];
    readonly name: "TokenHoldingsMerged";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "from";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "tokenType";
        readonly type: "uint256";
      }
    ];
    readonly name: "TokenTypeBurned";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "to";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "tokenType";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      }
    ];
    readonly name: "TokenTypeMinted";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "from";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "to";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "tokenType";
        readonly type: "uint256";
      }
    ];
    readonly name: "TokenTypeTransferred";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "from";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "to";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "value";
        readonly type: "uint256";
      }
    ];
    readonly name: "Transfer";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "oldRules";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "newRules";
        readonly type: "address";
      }
    ];
    readonly name: "Upgrade";
    readonly type: "event";
  },
  {
    readonly stateMutability: "nonpayable";
    readonly type: "fallback";
  },
  {
    readonly inputs: readonly [];
    readonly name: "MAX_CANCELABLE_BY";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "MAX_WALLETS_PER_HOLDER";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "_IIDENTITY_REGISTRY_INTERFACE_ID";
    readonly outputs: readonly [
      {
        readonly internalType: "bytes4";
        readonly name: "";
        readonly type: "bytes4";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "_ITRANSFER_RULES_INTERFACE_ID";
    readonly outputs: readonly [
      {
        readonly internalType: "bytes4";
        readonly name: "";
        readonly type: "bytes4";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "accessControl";
    readonly outputs: readonly [
      {
        readonly internalType: "contract IAccessControl";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "owner";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "spender";
        readonly type: "address";
      }
    ];
    readonly name: "allowance";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "spender";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "value";
        readonly type: "uint256";
      }
    ];
    readonly name: "approve";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "account";
        readonly type: "address";
      }
    ];
    readonly name: "balanceOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timelockIndex_";
        readonly type: "uint256";
      }
    ];
    readonly name: "balanceOfTimelock";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "recipients";
        readonly type: "address[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "amounts";
        readonly type: "uint256[]";
      }
    ];
    readonly name: "batchTransfer";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "target_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timelockIndex_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "scheduleId_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "commencementTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "totalAmount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "address";
        readonly name: "reclaimTokenTo_";
        readonly type: "address";
      }
    ];
    readonly name: "cancelTimelock";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "circulatingTokenSupply";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "_circulatingTokenSupply";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "contractVersion";
    readonly outputs: readonly [
      {
        readonly internalType: "string";
        readonly name: "";
        readonly type: "string";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "decimals";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "deploymentDay";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "from_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "value_";
        readonly type: "uint256";
      }
    ];
    readonly name: "detectTransferRestriction";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "tokenType_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "mintTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly components: readonly [
          {
            readonly internalType: "uint256[]";
            readonly name: "regions";
            readonly type: "uint256[]";
          },
          {
            readonly internalType: "uint256";
            readonly name: "accreditationType";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "lastAmlKycChangeTimestamp";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "lastAccreditationChangeTimestamp";
            readonly type: "uint256";
          },
          {
            readonly internalType: "bool";
            readonly name: "amlKycPassed";
            readonly type: "bool";
          }
        ];
        readonly internalType: "struct IIdentityRegistry.IdentityInfo";
        readonly name: "recipientIdentity";
        readonly type: "tuple";
      },
      {
        readonly internalType: "bool";
        readonly name: "isAmlKycPassed_";
        readonly type: "bool";
      }
    ];
    readonly name: "detectTransferRestrictionFor";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "wallet";
        readonly type: "address";
      }
    ];
    readonly name: "determineTokenType";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "elementBitSize";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "from_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly name: "forceTransferBetween";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "globalIndex";
        readonly type: "uint256";
      }
    ];
    readonly name: "getTokenTypeAndMintTimestampFromGlobalIndex";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "tokenType";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "mintTimestamp";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "index";
        readonly type: "uint256";
      }
    ];
    readonly name: "getWalletIndexes";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      }
    ];
    readonly name: "getWalletIndexesLength";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "globalHoldingCount";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly name: "globalMintTimestamps";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "holderCount";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "holderMax";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "identityRegistry";
    readonly outputs: readonly [
      {
        readonly internalType: "contract IIdentityRegistry";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "wallet";
        readonly type: "address";
      }
    ];
    readonly name: "isAmlKycPassed";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "isPaused";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "forwarder";
        readonly type: "address";
      }
    ];
    readonly name: "isTrustedForwarder";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      }
    ];
    readonly name: "lockedBalanceOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timelockIndex_";
        readonly type: "uint256";
      }
    ];
    readonly name: "lockedBalanceOfTimelock";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "_locked";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "maxBalancePerSubIndex";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "maxReleaseDelay";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "maxTotalSupply";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "restrictionCode_";
        readonly type: "uint256";
      }
    ];
    readonly name: "messageForTransferRestriction";
    readonly outputs: readonly [
      {
        readonly internalType: "string";
        readonly name: "";
        readonly type: "string";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "restrictionCode_";
        readonly type: "uint8";
      }
    ];
    readonly name: "messageForTransferRestriction";
    readonly outputs: readonly [
      {
        readonly internalType: "string";
        readonly name: "";
        readonly type: "string";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "minTimelockAmount";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "value_";
        readonly type: "uint256";
      }
    ];
    readonly name: "mint";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "mintTimestampCount";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "to";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "tokenType";
        readonly type: "uint256";
      }
    ];
    readonly name: "mintTokenType";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "name";
    readonly outputs: readonly [
      {
        readonly internalType: "string";
        readonly name: "";
        readonly type: "string";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "recordMintTimestamp";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "recordPausedOnDaysAfterDeployment";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "registryUnordered";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly name: "releaseSchedules";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "releaseCount";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "delayUntilFirstReleaseInSeconds";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "initialReleasePortionInBips";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "periodBetweenReleasesInSeconds";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "restrictedLockupTokenExtension";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "restrictedLockupTokenManagementExtension";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "restrictedLockupTokenStandardsExtension";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "scheduleCount";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "count";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "enabled";
        readonly type: "bool";
      }
    ];
    readonly name: "setRecordMintTimestamp";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "slotsPerWord";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "snapshotPeriods";
    readonly outputs: readonly [
      {
        readonly internalType: "contract ISnapshotPeriods";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "snapshotPeriodsAddress";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "snapshotsEnabled";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      }
    ];
    readonly name: "superBalanceOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "bytes4";
        readonly name: "interfaceId_";
        readonly type: "bytes4";
      }
    ];
    readonly name: "supportsInterface";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "symbol";
    readonly outputs: readonly [
      {
        readonly internalType: "string";
        readonly name: "";
        readonly type: "string";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      }
    ];
    readonly name: "timelockCountOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "index_";
        readonly type: "uint256";
      }
    ];
    readonly name: "timelockOf";
    readonly outputs: readonly [
      {
        readonly components: readonly [
          {
            readonly internalType: "address";
            readonly name: "funder";
            readonly type: "address";
          },
          {
            readonly internalType: "uint256";
            readonly name: "scheduleId";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "commencementTimestamp";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "tokensTransferred";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "totalAmount";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "globalHoldingIndex";
            readonly type: "uint256";
          },
          {
            readonly internalType: "address[]";
            readonly name: "cancelableBy";
            readonly type: "address[]";
          }
        ];
        readonly internalType: "struct Storage.Timelock";
        readonly name: "";
        readonly type: "tuple";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "account";
        readonly type: "address";
      }
    ];
    readonly name: "totalBalanceOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "balance";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "totalSupply";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timelockIndex_";
        readonly type: "uint256";
      }
    ];
    readonly name: "totalUnlockedToDateOfTimelock";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly name: "transfer";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "from_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly name: "transferFrom";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "to";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "globalHoldingIdx";
        readonly type: "uint256";
      }
    ];
    readonly name: "transferHolding";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "transferRules";
    readonly outputs: readonly [
      {
        readonly internalType: "contract ITransferRules";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timelockId_";
        readonly type: "uint256";
      }
    ];
    readonly name: "transferTimelock";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "trustedForwarder";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "unissuedTokenSupply";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "_unissuedTokenSupply";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      }
    ];
    readonly name: "unlockedBalanceOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timelockIndex_";
        readonly type: "uint256";
      }
    ];
    readonly name: "unlockedBalanceOfTimelock";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "_unlocked";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      }
    ];
    readonly name: "unlockedTotalBalanceOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "trustedForwarder_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "maxTotalSupply_";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "constructor";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveSoftBurnAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "to_";
        readonly type: "address[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "amounts_";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "commencementTimestamps_";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "scheduleIds_";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "address[]";
        readonly name: "cancelableBy_";
        readonly type: "address[]";
      }
    ];
    readonly name: "batchFundReleaseSchedule";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly components: readonly [
          {
            readonly internalType: "address";
            readonly name: "to";
            readonly type: "address";
          },
          {
            readonly internalType: "uint256";
            readonly name: "amount";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "commencementTimestamp";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "scheduleId";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "holdingIdx";
            readonly type: "uint256";
          }
        ];
        readonly internalType: "struct RestrictedLockupTokenExtension.FundReleaseScheduleParams[]";
        readonly name: "params";
        readonly type: "tuple[]";
      },
      {
        readonly internalType: "address[]";
        readonly name: "cancelableBy_";
        readonly type: "address[]";
      }
    ];
    readonly name: "batchFundReleaseScheduleWithHolding";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "to";
        readonly type: "address[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "amounts";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "commencementTimestamps";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "scheduleIds";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "address[]";
        readonly name: "cancelableBy";
        readonly type: "address[]";
      }
    ];
    readonly name: "batchMintReleaseSchedule";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "to";
        readonly type: "address[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "amounts";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "commencementTimestamps";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "scheduleIds";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "tokenTypes";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "address[]";
        readonly name: "cancelableBy";
        readonly type: "address[]";
      }
    ];
    readonly name: "batchMintReleaseScheduleTokenType";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "from_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "value_";
        readonly type: "uint256";
      }
    ];
    readonly name: "burn";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "from_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "globalHoldingIdx";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      }
    ];
    readonly name: "burnHolding";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "releaseCount";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "delayUntilFirstReleaseInSeconds";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "initialReleasePortionInBips";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "periodBetweenReleasesInSeconds";
        readonly type: "uint256";
      }
    ];
    readonly name: "createReleaseSchedule";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "unlockScheduleId";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "sender_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "recipient_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly name: "findHoldingFor";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "commencementTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "scheduleId_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "address[]";
        readonly name: "cancelableBy_";
        readonly type: "address[]";
      }
    ];
    readonly name: "fundReleaseSchedule";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "_success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly components: readonly [
          {
            readonly internalType: "address";
            readonly name: "to";
            readonly type: "address";
          },
          {
            readonly internalType: "uint256";
            readonly name: "amount";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "commencementTimestamp";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "scheduleId";
            readonly type: "uint256";
          },
          {
            readonly internalType: "uint256";
            readonly name: "holdingIdx";
            readonly type: "uint256";
          }
        ];
        readonly internalType: "struct RestrictedLockupTokenExtension.FundReleaseScheduleParams";
        readonly name: "params";
        readonly type: "tuple";
      },
      {
        readonly internalType: "address[]";
        readonly name: "cancelableBy_";
        readonly type: "address[]";
      }
    ];
    readonly name: "fundReleaseScheduleWithHolding";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "_success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "commencementTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "scheduleId_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "address[]";
        readonly name: "cancelableBy_";
        readonly type: "address[]";
      }
    ];
    readonly name: "mintReleaseSchedule";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "_success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "to_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "commencementTimestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "scheduleId_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "tokenType_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "address[]";
        readonly name: "cancelableBy_";
        readonly type: "address[]";
      }
    ];
    readonly name: "mintReleaseScheduleTokenType";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "_success";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "spender_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "value_";
        readonly type: "uint256";
      }
    ];
    readonly name: "safeApprove";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "maxTotalSupply_";
        readonly type: "uint256";
      }
    ];
    readonly name: "setMaxTotalSupply";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "from_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "value_";
        readonly type: "uint256";
      }
    ];
    readonly name: "softBurn";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "wallet";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "oldTokenType";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "newTokenType";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "globalIndex";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      }
    ];
    readonly name: "updateHoldingTokenType";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "wallet";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timelockIndex";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "newTokenType";
        readonly type: "uint256";
      }
    ];
    readonly name: "updateTimelockTokenType";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveContractAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveContractOrTransferAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "addresses_";
        readonly type: "address[]";
      }
    ];
    readonly name: "addHolderWithAddresses";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "_holderId";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr_";
        readonly type: "address";
      }
    ];
    readonly name: "addressHasHolder";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "holderId_";
        readonly type: "uint256";
      }
    ];
    readonly name: "appendHolderAddress";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "addresses_";
        readonly type: "address[]";
      }
    ];
    readonly name: "batchRemoveWalletFromHolder";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr_";
        readonly type: "address";
      }
    ];
    readonly name: "createHolderFromAddress";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "_holderId";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "index";
        readonly type: "uint256";
      }
    ];
    readonly name: "existingTokenTypes";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "existingTokenTypesCount";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr_";
        readonly type: "address";
      },
      {
        readonly internalType: "bool";
        readonly name: "status_";
        readonly type: "bool";
      }
    ];
    readonly name: "freeze";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr_";
        readonly type: "address";
      }
    ];
    readonly name: "getFrozenStatus";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "status";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "holderId_";
        readonly type: "uint256";
      }
    ];
    readonly name: "getHolderAddresses";
    readonly outputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "";
        readonly type: "address[]";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr_";
        readonly type: "address";
      }
    ];
    readonly name: "getHolderId";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "holderId_";
        readonly type: "uint256";
      }
    ];
    readonly name: "holderExists";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      }
    ];
    readonly name: "holdingCountOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "who_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "index_";
        readonly type: "uint256";
      }
    ];
    readonly name: "holdingOf";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "identityRegistryAddr_";
        readonly type: "address";
      }
    ];
    readonly name: "isValidIdentityRegistry";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "transferRulesAddr_";
        readonly type: "address";
      }
    ];
    readonly name: "isValidTransferRules";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "isPaused_";
        readonly type: "bool";
      }
    ];
    readonly name: "pause";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "from";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "to";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "expectedTransferableAmount";
        readonly type: "uint256";
      }
    ];
    readonly name: "previewTransferableFromHoldings";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "transferableAmount";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "holderId_";
        readonly type: "uint256";
      }
    ];
    readonly name: "removeHolder";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr_";
        readonly type: "address";
      }
    ];
    readonly name: "removeWalletFromHolder";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "holderMax_";
        readonly type: "uint256";
      }
    ];
    readonly name: "setHolderMax";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "tokenType";
        readonly type: "uint256";
      }
    ];
    readonly name: "tokenTypeExists";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "contract IIdentityRegistry";
        readonly name: "newIdentityRegistry";
        readonly type: "address";
      }
    ];
    readonly name: "upgradeIdentityRegistry";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "contract ITransferRules";
        readonly name: "newTransferRules";
        readonly type: "address";
      }
    ];
    readonly name: "upgradeTransferRules";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "ECDSAInvalidSignature";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "length";
        readonly type: "uint256";
      }
    ];
    readonly name: "ECDSAInvalidSignatureLength";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "bytes32";
        readonly name: "s";
        readonly type: "bytes32";
      }
    ];
    readonly name: "ECDSAInvalidSignatureS";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "deadline";
        readonly type: "uint256";
      }
    ];
    readonly name: "ERC2612ExpiredSignature";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "signer";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "owner";
        readonly type: "address";
      }
    ];
    readonly name: "ERC2612InvalidSigner";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "DOMAIN_SEPARATOR";
    readonly outputs: readonly [
      {
        readonly internalType: "bytes32";
        readonly name: "";
        readonly type: "bytes32";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "owner_";
        readonly type: "address";
      }
    ];
    readonly name: "nonces";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "owner_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "spender";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "value";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "deadline";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint8";
        readonly name: "v";
        readonly type: "uint8";
      },
      {
        readonly internalType: "bytes32";
        readonly name: "r";
        readonly type: "bytes32";
      },
      {
        readonly internalType: "bytes32";
        readonly name: "s";
        readonly type: "bytes32";
      }
    ];
    readonly name: "permit";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  }
];
