/**
 * Write the typed ABI modules that a viem or abitype consumer needs.
 *
 * abitype reads event and function names out of a literal type. A JSON
 * import widens every `"type": "uint256"` to `string`, which no longer
 * satisfies Abi, so a consumer that imports the ABI as JSON loses all of
 * the names and has to keep its own hand-written copy.
 *
 * Each module is a pair. The declaration carries the literal type. The
 * runtime file re-exports the JSON that the release already ships, so the
 * ABI bytes appear once in the package however many modules read them.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { loadJson, resolveReleaseDir } from './artifacts'
import type { ReleaseCatalogEntry } from './config'
import type { GeneratedFile } from './generate_abis'
import { parseManifest } from './manifest'

interface AbiModuleEntry {
  /** The exported name, such as `restrictedLockupTokenAbi`. */
  name: string
  /** The JSON to read at run time, relative to the release directory. */
  path: string
}

/**
 * RestrictedLockupToken -> restrictedLockupTokenAbi
 * ERC2771CustomForwarder -> erc2771CustomForwarderAbi
 */
export function exportName(contract: string): string {
  // A leading run of capitals is one word, except for the capital that
  // starts the next one.
  const acronym = /^[A-Z0-9]+(?=[A-Z][a-z])/.exec(contract)
  if (acronym !== null) {
    const head = acronym[0]
    return `${head.toLowerCase()}${contract.slice(head.length)}Abi`
  }
  if (/^[A-Z0-9]+$/.test(contract)) {
    return `${contract.toLowerCase()}Abi`
  }
  return `${contract.charAt(0).toLowerCase()}${contract.slice(1)}Abi`
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

function propertyName(key: string): string {
  return IDENTIFIER.test(key) ? key : JSON.stringify(key)
}

/**
 * The type of one JSON value, written out so that every string stays a
 * literal and every array stays a fixed-length readonly tuple. This is
 * what `as const` would infer, which is what abitype matches on.
 */
export function literalType(value: unknown, indent = ''): string {
  const inner = `${indent}  `

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return 'readonly []'
    }
    const items = value.map(item => `${inner}${literalType(item, inner)}`)
    return `readonly [\n${items.join(',\n')}\n${indent}]`
  }

  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value)
    if (entries.length === 0) {
      return 'Record<string, never>'
    }
    const fields = entries.map(
      ([key, item]) =>
        `${inner}readonly ${propertyName(key)}: ${literalType(item, inner)}`,
    )
    return `{\n${fields.join(';\n')};\n${indent}}`
  }

  return JSON.stringify(value)
}

function declarationFile(
  entries: AbiModuleEntry[],
  release: string,
  note: string[],
  releaseDir: string,
): string {
  const body = entries
    .map(entry => {
      const abi = loadJson(join(releaseDir, entry.path))
      return `export declare const ${entry.name}: ${literalType(abi)};`
    })
    .join('\n')

  return `${header(release, note)}\n${body}\n`
}

function runtimeFile(
  entries: AbiModuleEntry[],
  release: string,
  note: string[],
): string {
  const body = entries
    .map(entry => `exports.${entry.name} = require('../${entry.path}')`)
    .join('\n')

  return `${header(release, note)}\n'use strict'\n${body}\n`
}

function header(release: string, note: string[]): string {
  return [
    '// Generated by the contract-artifacts CLI. Do not edit.',
    `// Release ${release}.`,
    '//',
    ...note.map(line => `// ${line}`),
  ].join('\n')
}

const PLAIN_NOTE = [
  'The ABI of each contract in this release, as its own declaration.',
]

const MERGED_NOTE = [
  'The merged call surfaces. A token forwards unknown selectors into its',
  'extensions, so a caller that talks to the token address needs this',
  'rather than the token ABI alone.',
]

/**
 * The modules for a packed release directory, with paths relative to that
 * directory. The manifest names the release and every ABI, so this needs
 * nothing but the directory.
 */
export function typedAbiModules(releaseDir: string): GeneratedFile[] {
  const manifestPath = join(releaseDir, 'manifest.json')
  if (!existsSync(manifestPath)) {
    throw new Error(`Missing ${manifestPath}`)
  }
  const manifest = parseManifest(loadJson(manifestPath))

  const plain = manifest.artifacts.map(artifact => ({
    name: exportName(artifact.name),
    path: artifact.abi.path,
  }))
  const merged = manifest.callSurfaces.map(surface => ({
    name: exportName(surface.name),
    path: surface.abi.path,
  }))

  const files: GeneratedFile[] = []
  const emit = (
    module: string,
    entries: AbiModuleEntry[],
    note: string[],
  ): void => {
    if (entries.length === 0) {
      return
    }
    files.push({
      path: join('typed', `${module}.d.ts`),
      contents: declarationFile(entries, manifest.releaseId, note, releaseDir),
    })
    files.push({
      path: join('typed', `${module}.js`),
      contents: runtimeFile(entries, manifest.releaseId, note),
    })
  }

  emit('abis', plain, PLAIN_NOTE)
  emit('merged', merged, MERGED_NOTE)
  return files
}

/** Write the modules into a release directory, as packing does. */
export function writeTypedAbiModules(releaseDir: string): GeneratedFile[] {
  const files = typedAbiModules(releaseDir)
  for (const file of files) {
    const dest = join(releaseDir, file.path)
    mkdirSync(dirname(dest), { recursive: true })
    writeFileSync(dest, file.contents, 'utf8')
  }
  return files
}

/**
 * The same modules with paths relative to the config root, which is what
 * the audit and the drift check read.
 */
export function generateTypedAbisForRelease(
  entry: ReleaseCatalogEntry,
): GeneratedFile[] {
  const releaseDir = resolveReleaseDir(entry)
  if (releaseDir === undefined || entry.releaseDir === undefined) {
    throw new Error(`Release ${entry.releaseId} has no packed directory`)
  }
  const prefix = entry.releaseDir
  return typedAbiModules(releaseDir).map(file => ({
    path: join(prefix, file.path),
    contents: file.contents,
  }))
}
