// Generated by the contract-artifacts CLI. Do not edit.
// Release evm/comakery_security_token_v5/2026-09-17-quantstamp.
//
// The ABI of each contract in this release, as its own declaration.
'use strict'
exports.accessControlAbi = require('../abi/AccessControl.json')
exports.erc2771CustomForwarderAbi = require('../abi/ERC2771CustomForwarder.json')
exports.identityRegistryAbi = require('../abi/IdentityRegistry.json')
exports.interestPaymentAbi = require('../abi/InterestPayment.json')
exports.purchaseContractAbi = require('../abi/PurchaseContract.json')
exports.restrictedLockupTokenAbi = require('../abi/RestrictedLockupToken.json')
exports.restrictedLockupTokenExtensionAbi = require('../abi/RestrictedLockupTokenExtension.json')
exports.restrictedLockupTokenManagementExtensionAbi = require('../abi/RestrictedLockupTokenManagementExtension.json')
exports.restrictedSwapAbi = require('../abi/RestrictedSwap.json')
exports.snapshotPeriodsAbi = require('../abi/SnapshotPeriods.json')
exports.transferRulesAbi = require('../abi/TransferRules.json')
