// Generated by the contract-artifacts CLI. Do not edit.
// Release evm/recallable_payment/v1.0.0.
//
// The ABI of each contract in this release, as its own declaration.
'use strict'
exports.accessControlAbi = require('../abi/AccessControl.json')
exports.recallablePaymentAbi = require('../abi/RecallablePayment.json')
