// Generated by the contract-artifacts CLI. Do not edit.
// Release evm/recallable_payment/v1.0.0.
//
// The ABI of each contract in this release, as its own declaration.
export declare const accessControlAbi: readonly [
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "contractAdmin_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "reserveAdmin_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "transferAdmin_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "trustedForwarder_";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "constructor";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EasyAccessControl_AlreadyHasRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EasyAccessControl_ArraysMustBeSameLength";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EasyAccessControl_AtLeastOneContractAdminRequired";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EasyAccessControl_CannotRevokeRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveContractAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EasyAccessControl_InvalidRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EasyAccessControl_InvalidZeroAddress";
    readonly type: "error";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "grantor";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "grantee";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint8";
        readonly name: "role";
        readonly type: "uint8";
      },
      {
        readonly indexed: true;
        readonly internalType: "bool";
        readonly name: "status";
        readonly type: "bool";
      }
    ];
    readonly name: "RoleChange";
    readonly type: "event";
  },
  {
    readonly inputs: readonly [];
    readonly name: "CONTRACT_ADMIN_ROLE";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "MINT_ADMIN_ROLE";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RESERVE_ADMIN_ROLE";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "SOFT_BURN_ADMIN_ROLE";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "TRANSFER_ADMIN_ROLE";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "WALLETS_ADMIN_ROLE";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "addresses";
        readonly type: "address[]";
      },
      {
        readonly internalType: "uint8[]";
        readonly name: "roles_";
        readonly type: "uint8[]";
      }
    ];
    readonly name: "batchGrantRoles";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address[]";
        readonly name: "addresses";
        readonly type: "address[]";
      },
      {
        readonly internalType: "uint8[]";
        readonly name: "roles_";
        readonly type: "uint8[]";
      }
    ];
    readonly name: "batchRevokeRoles";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "contractAdminCount";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      },
      {
        readonly internalType: "uint8";
        readonly name: "role";
        readonly type: "uint8";
      }
    ];
    readonly name: "grantRole";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      },
      {
        readonly internalType: "uint8";
        readonly name: "role";
        readonly type: "uint8";
      }
    ];
    readonly name: "hasRole";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "forwarder";
        readonly type: "address";
      }
    ];
    readonly name: "isTrustedForwarder";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      },
      {
        readonly internalType: "uint8";
        readonly name: "role";
        readonly type: "uint8";
      }
    ];
    readonly name: "revokeRole";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "roles";
    readonly outputs: readonly [
      {
        readonly internalType: "uint8";
        readonly name: "";
        readonly type: "uint8";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "trustedForwarder";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  }
];
export declare const recallablePaymentAbi: readonly [
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "accessControl_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "trustedForwarder_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "restrictedLockupToken_";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "nonpayable";
    readonly type: "constructor";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveContractAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveContractOrTransferAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "addr";
        readonly type: "address";
      }
    ];
    readonly name: "EasyAccessControl_DoesNotHaveTransferAdminRole";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EasyAccessControl_InvalidZeroAddress";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "EnforcedPause";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "ExpectedPause";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "index";
        readonly type: "uint256";
      }
    ];
    readonly name: "RecallablePayment_AllocationUnchanged";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_DistributionClaimingOpen";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_DistributionNotStarted";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_DistributionNotUnlocked";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_DividendsAlreadyClaimed";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_EmptyRecipients";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "requested";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "available";
        readonly type: "uint256";
      }
    ];
    readonly name: "RecallablePayment_InsufficientDistributionFunds";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "index";
        readonly type: "uint256";
      }
    ];
    readonly name: "RecallablePayment_InvalidAmount";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_InvalidArrayLengths";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_InvalidFeeApplied";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "index";
        readonly type: "uint256";
      }
    ];
    readonly name: "RecallablePayment_InvalidRecipientAddress";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_InvalidReclaimerAddress";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_InvalidTimestamp";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_InvalidTokenAddress";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_InvalidTrustedForwarder";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_InvalidWalletAddress";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_NoAllocationsToFund";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_NoFundsToClaim";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_NoPositionToTransfer";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_NoRemainingUnclaimedBalance";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_NotEnoughFundsToClaim";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "totalAllocated";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "totalFunds";
        readonly type: "uint256";
      }
    ];
    readonly name: "RecallablePayment_NotFullyFunded";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_ReclaimerAddressUnchanged";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "RecallablePayment_SameWallet";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "provided";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "scheduled";
        readonly type: "uint256";
      }
    ];
    readonly name: "RecallablePayment_UnlockTimeConflict";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "requested";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "current";
        readonly type: "uint256";
      }
    ];
    readonly name: "RecallablePayment_UnlockTimeNotApplicableAfterStart";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [];
    readonly name: "ReentrancyGuardReentrantCall";
    readonly type: "error";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      }
    ];
    readonly name: "SafeERC20FailedOperation";
    readonly type: "error";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "recipient";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      }
    ];
    readonly name: "AllocationUpdated";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "totalAllocated";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "totalFunds";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "unlockedAtTs";
        readonly type: "uint256";
      }
    ];
    readonly name: "DistributionStarted";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "unlockedAtTs";
        readonly type: "uint256";
      }
    ];
    readonly name: "DistributionUnlockTimeUpdated";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "payee";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      }
    ];
    readonly name: "DividendClaimed";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "wallet";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      }
    ];
    readonly name: "DividendForceClaimed";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "oldWallet";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "address";
        readonly name: "newWallet";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "allocatedAmount";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "claimedAmount";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "reclaimedAmount";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      }
    ];
    readonly name: "DividendForceTransferred";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "payer";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: true;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      }
    ];
    readonly name: "DividendFunded";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "payee";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "target";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "token";
        readonly type: "address";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "amount";
        readonly type: "uint256";
      },
      {
        readonly indexed: false;
        readonly internalType: "uint256";
        readonly name: "timestamp";
        readonly type: "uint256";
      }
    ];
    readonly name: "DividendReclaimed";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: false;
        readonly internalType: "address";
        readonly name: "account";
        readonly type: "address";
      }
    ];
    readonly name: "Paused";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "admin";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "previousReclaimer";
        readonly type: "address";
      },
      {
        readonly indexed: true;
        readonly internalType: "address";
        readonly name: "newReclaimer";
        readonly type: "address";
      }
    ];
    readonly name: "ReclaimerAddressChanged";
    readonly type: "event";
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: false;
        readonly internalType: "address";
        readonly name: "account";
        readonly type: "address";
      }
    ];
    readonly name: "Unpaused";
    readonly type: "event";
  },
  {
    readonly inputs: readonly [];
    readonly name: "accessControl";
    readonly outputs: readonly [
      {
        readonly internalType: "contract IAccessControl";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "recipient_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "allocatedBalanceAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "timestamps_";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "amounts_";
        readonly type: "uint256[]";
      }
    ];
    readonly name: "batchClaimDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "wallet_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "timestamps_";
        readonly type: "uint256[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "amounts_";
        readonly type: "uint256[]";
      }
    ];
    readonly name: "batchForceClaimDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly name: "claimDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "recipient_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "claimedBalanceAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "address[]";
        readonly name: "recipients_";
        readonly type: "address[]";
      },
      {
        readonly internalType: "uint256[]";
        readonly name: "amounts_";
        readonly type: "uint256[]";
      }
    ];
    readonly name: "createDistribution";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "wallet_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly name: "forceClaimDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "address";
        readonly name: "oldWallet_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "newWallet_";
        readonly type: "address";
      }
    ];
    readonly name: "forceTransferDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "unlockedAtTs_";
        readonly type: "uint256";
      }
    ];
    readonly name: "fundDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "fundDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "fundsAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "isClaimable";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "isStarted";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "forwarder";
        readonly type: "address";
      }
    ];
    readonly name: "isTrustedForwarder";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "shouldPause_";
        readonly type: "bool";
      }
    ];
    readonly name: "pause";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "paused";
    readonly outputs: readonly [
      {
        readonly internalType: "bool";
        readonly name: "";
        readonly type: "bool";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "targetAddress_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      }
    ];
    readonly name: "reclaimDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "reclaimSurplus";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "amount_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "reclaimTotalDividend";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "recipient_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "reclaimedBalanceAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "reclaimerAddress";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "restrictedLockupToken";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "newReclaimerAddress";
        readonly type: "address";
      }
    ];
    readonly name: "setReclaimerAddress";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      },
      {
        readonly internalType: "uint256";
        readonly name: "unlockedAtTs_";
        readonly type: "uint256";
      }
    ];
    readonly name: "setUnlockTime";
    readonly outputs: readonly [];
    readonly stateMutability: "nonpayable";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "tokensAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "totalAllocatedAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "recipient_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "totalAwardedBalanceAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [];
    readonly name: "trustedForwarder";
    readonly outputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "";
        readonly type: "address";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "address";
        readonly name: "recipient_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "unclaimedBalanceAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: "address";
        readonly name: "token_";
        readonly type: "address";
      },
      {
        readonly internalType: "uint256";
        readonly name: "timestamp_";
        readonly type: "uint256";
      }
    ];
    readonly name: "unlockTimeAt";
    readonly outputs: readonly [
      {
        readonly internalType: "uint256";
        readonly name: "";
        readonly type: "uint256";
      }
    ];
    readonly stateMutability: "view";
    readonly type: "function";
  }
];
